"""Constants originally defined in odbtp.h
"""

# ODB Data Definitions
ODB_BINARY = -2
ODB_BIGINT = -25
ODB_UBIGINT = -27
ODB_BIT = -7
ODB_CHAR = 1
ODB_DATE = 91
ODB_DATETIME = 93
ODB_DOUBLE = 8
ODB_FLOAT = 8
ODB_GUID = -11
ODB_INT = -16
ODB_UINT = -18
ODB_NUMERIC = 2
ODB_REAL = 7
ODB_SMALLINT = -15
ODB_USMALLINT = -17
ODB_TIME = 92
ODB_TINYINT = -26
ODB_UTINYINT = -28
ODB_WCHAR = -8

# SQL Data Types
SQL_BIT = -7
SQL_TINYINT = -6
SQL_SMALLINT = 5
SQL_INTEGER = 4
SQL_INT = 4
SQL_BIGINT = -5
SQL_NUMERIC = 2
SQL_REAL = 7
SQL_FLOAT = 6
SQL_DOUBLE = 8
SQL_DECIMAL = 3
SQL_DATE = 9
SQL_TIME = 10
SQL_TIMESTAMP = 11
SQL_TYPE_DATE = 91
SQL_TYPE_TIME = 92
SQL_TYPE_TIMESTAMP = 93
SQL_DATETIME = 93
SQL_CHAR = 1
SQL_VARCHAR = 12
SQL_LONGVARCHAR = -1
SQL_TEXT = -1
SQL_WCHAR = -8
SQL_NCHAR = -8
SQL_WVARCHAR = -9
SQL_NVARCHAR = -9
SQL_WLONGVARCHAR = -10
SQL_NTEXT = -10
SQL_BINARY = -2
SQL_VARBINARY = -3
SQL_LONGVARBINARY = -4
SQL_IMAGE = -4
SQL_GUID = -11
SQL_VARIANT = -150

# ODB Login Types
ODB_LOGIN_NORMAL = 0
ODB_LOGIN_RESERVED = 1
ODB_LOGIN_SINGLE = 2

# ODB Numeric Attributes
ODB_ATTR_DRIVER = 0
ODB_ATTR_FETCHROWCOUNT = 1
ODB_ATTR_TRANSACTIONS = 2
ODB_ATTR_DESCRIBEPARAMS = 3
ODB_ATTR_UNICODESQL = 4
ODB_ATTR_FULLCOLINFO = 5
ODB_ATTR_QUERYTIMEOUT = 6
ODB_ATTR_OICLEVEL = 7
ODB_ATTR_TXNCAPABLE = 8
ODB_ATTR_MAPCHARTOWCHAR = 9
ODB_ATTR_VARDATASIZE = 10
ODB_ATTR_CACHEPROCS = 11
ODB_ATTR_RIGHTTRIMTEXT = 12

# ODB String Attributes
ODB_ATTR_STRING = 0x10000
ODB_ATTR_DSN = (0|ODB_ATTR_STRING)
ODB_ATTR_DRIVERNAME = (1|ODB_ATTR_STRING)
ODB_ATTR_DRIVERVER = (2|ODB_ATTR_STRING)
ODB_ATTR_DRIVERODBCVER = (3|ODB_ATTR_STRING)
ODB_ATTR_DBMSNAME = (4|ODB_ATTR_STRING)
ODB_ATTR_DBMSVER = (5|ODB_ATTR_STRING)
ODB_ATTR_SERVERNAME = (6|ODB_ATTR_STRING)
ODB_ATTR_USERNAME = (7|ODB_ATTR_STRING)
ODB_ATTR_DATABASENAME = (8|ODB_ATTR_STRING)

# ODB ODBC Driver types
ODB_DRIVER_UNKNOWN = 0
ODB_DRIVER_MSSQL = 1
ODB_DRIVER_JET = 2
ODB_DRIVER_FOXPRO = 3
ODB_DRIVER_ORACLE = 4
ODB_DRIVER_SYBASE = 5
ODB_DRIVER_MYSQL = 6
ODB_DRIVER_DB2 = 7

# ODB Transaction Types
ODB_TXN_NONE = 0
ODB_TXN_READUNCOMMITTED = 1
ODB_TXN_READCOMMITTED = 2
ODB_TXN_REPEATABLEREAD = 3
ODB_TXN_SERIALIZABLE = 4
ODB_TXN_DEFAULT = 255

# ODB ODBC Interface Conformace Levels
ODB_OIC_CORE = 1
ODB_OIC_LEVEL1 = 2
ODB_OIC_LEVEL2 = 3

# ODB Col Info Flags
ODB_COLINFO_NOTNULL = 0x0001
ODB_COLINFO_UNSIGNED = 0x0002
ODB_COLINFO_AUTONUMBER = 0x0004
ODB_COLINFO_PRIMARYKEY = 0x0008
ODB_COLINFO_HIDDEN = 0x0010

# ODB Param Types
ODB_PARAM_NONE = 0x0000
ODB_PARAM_INPUT = 0x0001
ODB_PARAM_OUTPUT = 0x0002
ODB_PARAM_INOUT = (ODB_PARAM_INPUT | ODB_PARAM_OUTPUT)
ODB_PARAM_RETURNVAL = (0x0004 | ODB_PARAM_OUTPUT)
ODB_PARAM_RESULTCOL = 0x0008
ODB_PARAM_DESCRIBED = 0x8000

# ODB Length Indicators
ODB_NULL = -1
ODB_DEFAULT = -5
ODB_IGNORE = -6
ODB_TRUNCATION = 0xE0000001
ODB_SENTSYNC = 0xF000000F

# ODB Cursor Types
ODB_CURSOR_FORWARD = 0
ODB_CURSOR_STATIC = 1
ODB_CURSOR_KEYSET = 2
ODB_CURSOR_DYNAMIC = 3

# ODB Cursor Concurrency Types
ODB_CONCUR_DEFAULT = 0
ODB_CONCUR_READONLY = 1
ODB_CONCUR_LOCK = 2
ODB_CONCUR_ROWVER = 3
ODB_CONCUR_VALUES = 4

# ODB Fetch Types
ODB_FETCH_DEFAULT = 0
ODB_FETCH_FIRST = 1
ODB_FETCH_LAST = 2
ODB_FETCH_NEXT = 3
ODB_FETCH_PREV = 4
ODB_FETCH_ABS = 5
ODB_FETCH_REL = 6
ODB_FETCH_BOOKMARK = 7
ODB_FETCH_REREAD = 8

# ODB Row Operations
ODB_ROW_GETSTATUS = 0
ODB_ROW_REFRESH = 1
ODB_ROW_UPDATE = 2
ODB_ROW_DELETE = 3
ODB_ROW_ADD = 4
ODB_ROW_LOCK = 5
ODB_ROW_UNLOCK = 6
ODB_ROW_BOOKMARK = 7

# ODB Row Status Values
ODB_ROWSTAT_ERROR = 0
ODB_ROWSTAT_SUCCESS = 1
ODB_ROWSTAT_UPDATED = 2
ODB_ROWSTAT_DELETED = 3
ODB_ROWSTAT_ADDED = 4
ODB_ROWSTAT_NOROW = 5
ODB_ROWSTAT_UNKNOWN = 0xFFFFFFFF

# Error Codes
ODBTPERR_NONE = 0
ODBTPERR_MEMORY = 1
ODBTPERR_HANDLE = 2
ODBTPERR_CONNECT = 3
ODBTPERR_READ = 4
ODBTPERR_SEND = 5
ODBTPERR_TIMEOUTCONN = 6
ODBTPERR_TIMEOUTREAD = 7
ODBTPERR_TIMEOUTSEND = 8
ODBTPERR_CONNECTED = 9
ODBTPERR_PROTOCOL = 10
ODBTPERR_RESPONSE = 11
ODBTPERR_MAXQUERYS = 12
ODBTPERR_COLNUMBER = 13
ODBTPERR_COLNAME = 14
ODBTPERR_FETCHROW = 15
ODBTPERR_NOTPREPPROC = 16
ODBTPERR_NOPARAMINFO = 17
ODBTPERR_PARAMNUMBER = 18
ODBTPERR_PARAMNAME = 19
ODBTPERR_PARAMBIND = 20
ODBTPERR_PARAMGET = 21
ODBTPERR_ATTRTYPE = 22
ODBTPERR_GETQUERY = 23
ODBTPERR_INTERFFILE = 24
ODBTPERR_INTERFSYN = 25
ODBTPERR_INTERFTYPE = 26
ODBTPERR_CONNSTRLEN = 27
ODBTPERR_NOSEEKCURSOR = 28
ODBTPERR_SEEKROWPOS = 29
ODBTPERR_DETACHED = 30
ODBTPERR_GETTYPEINFO = 31
ODBTPERR_LOADTYPES = 32
ODBTPERR_NOREQUEST = 33
ODBTPERR_FETCHEDROWS = 34
ODBTPERR_DISCONNECTED = 35
ODBTPERR_HOSTRESOLVE = 36
ODBTPERR_SERVER = 100
